<?php

$npcinfo = array
	( 
	1 => array
		(
		'type' => 1,
		'num' => 1,
		'round' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 4000,
		'msp' => 200,
		'att' => 175,
		'def' => 275,
		'lvl' => 45,
		'proficiency' => 200,
		'skill' => array('Peg'),
		'money' => 5000,
		'arb' => '黑色遮羞布',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 100,
		'arh' => '黑色头巾',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 100,
		'arf' => '黑色裹脚布',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 100,
		'ara' => '黑色手带',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 100,
		'art' => '触手证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('buff-def' => 10),
		'sub' => array
			(
			0 => array
				(
				'name' => '.....',
				'icon' => 1,
				'wep' => '黑幕电磁炮',
				'wepk' => 'WG',
				'wepe' => 150,
				'weps' => 65535,
				'itm1' => '结界解除钥匙',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	2 => array
		(
		'type' => 2,
		'num' => 4,
		'round' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 2500,
		'msp' => 200,
		'att' => 150,
		'def' => 200,
		'lvl' => 20,
		'proficiency' => 150,
		'skill' => array('Peg'),
		'money' => 2000,
		'arb' => '触手服',
		'arbk' => 'DB',
		'arbe' => 40,
		'arbs' => 100,
		'arh' => '触手帽',
		'arhk' => 'DH',
		'arhe' => 20,
		'arhs' => 100,
		'arf' => '触手靴',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 100,
		'ara' => '触手用手套',
		'arak' => 'DA',
		'arae' => 20,
		'aras' => 100,
		'art' => '教师证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('buff-def' => 10),
		'sub' => array
			(
			0 => array
				(
				'name' => '吃',
				'icon' => 2,
				'wep' => '触手用狙击枪',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			1 => array
				(
				'name' => '污',
				'icon' => 2,
				'wep' => '触手用狙击枪',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			2 => array
				(
				'name' => '物',
				'icon' => 2,
				'wep' => '触手用狙击枪',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			3 => array
				(
				'name' => '触',
				'icon' => 2,
				'wep' => '触手用狙击枪',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			),
		),
	3 => array
		(
		'type' => 3,
		'mode' => 2,
		'num' => 45,
		'round' => 0,
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 100,
		'msp' => 200,
		'att' => 100,
		'def' => 75,
		'lvl' => 5,
		'proficiency' => 20,
		'skill' => array('kedama'),
		'lastword' => '',
		'money' => 80,
		'sub' => array
			(
			0 => array
				(
				'name' => '小毛玉',
				'icon' => 101,
				'wep' => '毛玉弹弓β',
				'wepk' => 'WG',
				'wepe' => 5,
				'weps' => 12,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '毛玉饮料β',
				'itmk1' => 'HS',
				'itme1' => 150,
				'itms1' => 1,
				),
			1 => array
				(
				'name' => '小毛玉',
				'icon' => 103,
				'wep' => '木棍',
				'wepk' => 'WP',
				'wepe' => 1,
				'weps' => 2,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '毛玉草药β',
				'itmk1' => 'HH',
				'itme1' => 150,
				'itms1' => 1,
				),
			2 => array
				(
				'name' => '小毛玉',
				'icon' => 102,
				'wep' => '玻璃渣',
				'wepk' => 'WK',
				'wepe' => 1,
				'weps' => 3,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '毛玉干粮β',
				'itmk1' => 'HB',
				'itme1' => 75,
				'itms1' => 1,
				),
			3 => array
				(
				'name' => '小毛玉',
				'icon' => 104,
				'wep' => '石子',
				'wepk' => 'WC',
				'wepe' => 1,
				'weps' => 12,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '解毒剂',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	4 => array
		(
		'type' => 3,
		'mode' => 2,
		'num' => 60,
		'round' => 0,
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 200,
		'msp' => 200,
		'att' => 125,
		'def' => 100,
		'lvl' => 10,
		'proficiency' => 40,
		'skill' => array('kedama'),
		'money' => 250,
		'wepsk' => array('suit' => 'kedama'),
		'sub' => array
			(
			0 => array
				(
				'name' => '毛玉',
				'icon' => 105,
				'wep' => '毛玉弹弓α',
				'wepk' => 'WG',
				'wepe' => 10,
				'weps' => 18,
				'wepsk' => array('suit' => 'kedama'),
				'arb' => '毛玉外套',
				'arbk' => 'DB',
				'arbe' => 25,
				'arbs' => 20,
				'arbsk' => array('suit' => 'kedama'),
				'itm1' => '毛玉饮料α',
				'itmk1' => 'HS',
				'itme1' => 125,
				'itms1' => 1,
				),
			1 => array
				(
				'name' => '毛玉',
				'icon' => 107,
				'wep' => '石棍',
				'wepk' => 'WP',
				'wepe' => 5,
				'weps' => 3,
				'wepsk' => array('suit' => 'kedama'),
				'ara' => '毛玉手套',
				'arak' => 'DA',
				'arae' => 10,
				'aras' => 10,
				'arask' => array('suit' => 'kedama'),
				'itm1' => '毛玉草药α',
				'itmk1' => 'HH',
				'itme1' => 175,
				'itms1' => 1,
				),
			2 => array
				(
				'name' => '毛玉',
				'icon' => 106,
				'wep' => '瓷片',
				'wepk' => 'WK',
				'wepe' => 5,
				'weps' => 5,
				'wepsk' => array('suit' => 'kedama'),
				'arf' => '毛玉织袜',
				'arfk' => 'DF',
				'arfe' => 10,
				'arfs' => 10,
				'arfsk' => array('suit' => 'kedama'),
				'itm1' => '毛玉干粮α',
				'itmk1' => 'HB',
				'itme1' => 100,
				'itms1' => 1,
				),
			3 => array
				(
				'name' => '毛玉',
				'icon' => 108,
				'wep' => '钢珠',
				'wepk' => 'WC',
				'wepe' => 5,
				'weps' => 18,
				'wepsk' => array('suit' => 'kedama'),
				'arh' => '毛玉棉帽',
				'arhk' => 'DH',
				'arhe' => 10,
				'arhs' => 10,
				'arhsk' => array('suit' => 'kedama'),
				'itm1' => '毒药',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	5 => array
		(
		'type' => 3,
		'num' => 1,
		'round' => 0,
		'gd' => 'r',
		'pls' => 14,
		'mhp' => 500,
		'msp' => 200,
		'att' => 150,
		'def' => 100,
		'lvl' => 15,
		'proficiency' => 60,
		'skill' => array('kedama', 'Peg','disappear@1'),
		'money' => 500,
		'arb' => '毛玉外套',
		'arbk' => 'DB',
		'arbe' => 25,
		'arbs' => 20,
		'arbsk' => array('suit' => 'kedama'),
		'ara' => '毛玉手套',
		'arak' => 'DA',
		'arae' => 10,
		'aras' => 10,
		'arask' => array('suit' => 'kedama'),
		'arf' => '毛玉织袜',
		'arfk' => 'DF',
		'arfe' => 10,
		'arfs' => 10,
		'arfsk' => array('suit' => 'kedama'),
		'arh' => '毛玉棉帽',
		'arhk' => 'DH',
		'arhe' => 10,
		'arhs' => 10,
		'arhsk' => array('suit' => 'kedama'),
		'art' => '毛玉之证',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('suit' => 'kedama', 'att-buff' => 20),
		'sub' => array
			(
			0 => array
				(
				'name' => '飞空毛玉',
				'icon' => 119,
				'wep' => '毛玉符',
				'wepk' => 'WD',
				'wepe' => 40,
				'weps' => 30,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '萌',
				'itmk1' => 'Y',
				'itme1' => 50,
				'itms1' => 1,
				),
			),
		),
	19 => array
		(
		'type' => 3,
		'mode' => 2,
		'num' => 120,
		'round' => 1,
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 450,
		'msp' => 200,
		'att' => 125,
		'def' => 160,
		'lvl' => 15,
		'proficiency' => 115,
		'skill' => array('kedama'),
		'money' => 500,
		'arb' => '毛玉战甲',
		'arbk' => 'DB',
		'arbe' => 35,
		'arbs' => 30,
		'arbsk' => array('suit' => 'kedama'),
		'arh' => '毛玉战帽',
		'arhk' => 'DH',
		'arhe' => 15,
		'arhs' => 30,
		'arhsk' => array('suit' => 'kedama'),
		'arf' => '毛玉战靴',
		'arfk' => 'DF',
		'arfe' => 15,
		'arfs' => 30,
		'arfsk' => array('suit' => 'kedama'),
		'ara' => '毛玉护手',
		'arak' => 'DA',
		'arae' => 15,
		'aras' => 30,
		'arask' => array('suit' => 'kedama'),
		'art' => '毛玉证明书',
		'artk' => 'A',
		'arte' => 30,
		'arts' => 10,
		'artsk' => array('def-buff' => 30, 'suit' => 'kedama'),
		'wepsk' => array('suit' => 'kedama'),
		'sub' => array
			(
			0 => array
				(
				'name' => '毛玉战士',
				'icon' => 109,
				'wep' => '毛玉左轮',
				'wepk' => 'WG',
				'wepe' => 35,
				'weps' => 20,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '粮食包',
				'itmk1' => 'HS',
				'itme1' => 175,
				'itms1' => 1,
				),
			1 => array
				(
				'name' => '毛玉战士',
				'icon' => 110,
				'wep' => '毛玉棍',
				'wepk' => 'WP',
				'wepe' => 30,
				'weps' => 5,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '急救包',
				'itmk1' => 'HH',
				'itme1' => 200,
				'itms1' => 1,
				),
			2 => array
				(
				'name' => '毛玉战士',
				'icon' => 111,
				'wep' => '毛玉片手',
				'wepk' => 'WK',
				'wepe' => 35,
				'weps' => 10,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '干粮包',
				'itmk1' => 'HB',
				'itme1' => 125,
				'itms1' => 1,
				),
			3 => array
				(
				'name' => '毛玉战士',
				'icon' => 112,
				'wep' => '毛玉镖',
				'wepk' => 'WC',
				'wepe' => 10,
				'weps' => 25,
				'wepsk' => array('suit' => 'kedama'),
				'itm1' => '解毒剂',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	20 => array
		(
		'type' => 3,
		'mode' => 2,
		'num' => 10,
		'round' => 2,
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 1250,
		'msp' => 500,
		'att' => 200,
		'def' => 250,
		'lvl' => 30,
		'proficiency' => 200,
		'skill' => array('kedama'),
		'money' => 1500,
		'arb' => '毛玉鳞甲',
		'arbk' => 'DB',
		'arbe' => 60,
		'arbs' => 30,
		'arbsk' => array('suit' => 'kedama'),
		'arh' => '毛玉钢盔',
		'arhk' => 'DH',
		'arhe' => 30,
		'arhs' => 30,
		'arhsk' => array('suit' => 'kedama'),
		'arf' => '毛玉战靴',
		'arfk' => 'DF',
		'arfe' => 30,
		'arfs' => 30,
		'arfsk' => array('suit' => 'kedama'),
		'ara' => '毛玉护盾',
		'arak' => 'DA',
		'arae' => 20,
		'aras' => 30,
		'arask' => array('suit' => 'kedama', 'shield' => 20),
		'art' => '毛玉之证',
		'artk' => 'A',
		'arte' => 25,
		'arts' => 10,
		'artsk' => array('suit' => 'kedama', 'att-buff' => 25),
		'itm1' => '毛玉票',
		'itmk1' => 'HB',
		'itme1' => 400,
		'itms1' => 1,
		'name' => '毛玉之王',
		'icon' => 120,
		'wepsk' => array('suit' => 'kedama'),
		'sub' => array(
			0 => array
				(
				'wep' => '毛玉连弩',
				'wepk' => 'WG',
				'wepe' => 55,
				'weps' => 30,
				'wepsk' => array('suit' => 'kedama'),
				),
			1 => array
				(
				'wep' => '毛玉格斗短棍',
				'wepk' => 'WP',
				'wepe' => 35,
				'weps' => 10,
				'wepsk' => array('suit' => 'kedama'),
				),
			2 => array
				(
				'wep' => '毛玉太刀',
				'wepk' => 'WK',
				'wepe' => 30,
				'weps' => 15,
				'wepsk' => array('suit' => 'kedama'),
				),
			3 => array
				(
				'wep' => '毛玉标枪',
				'wepk' => 'WC',
				'wepe' => 20,
				'weps' => 30,
				'wepsk' => array('suit' => 'kedama'),
				),
			4 => array
				(
				'wep' => '毛玉手雷',
				'wepk' => 'WD',
				'wepe' => 60,
				'weps' => 20,
				'wepsk' => array('suit' => 'kedama'),
				),
			),
		),
	7 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 15,
		'mhp' => 450,
		'msp' => 400,
		'att' => 125,
		'def' => 150,
		'lvl' => 20,
		'proficiency' => 100,
		'skill' => array('Peg'),
		'money' => 1250,
		'arb' => '妖梦·灵服',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'konpaku'),
		'arh' => '妖梦·缎带',
		'arhk' => 'DH',
		'arhe' => 15,
		'arhs' => 20,
		'arhsk' => array('suit' => 'konpaku'),
		'arf' => '妖梦·布鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'konpaku'),
		'ara' => '妖梦·剑鞘',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		'arask' => array('suit' => 'konpaku'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '魂魄妖夢',
				'icon' => 22,
				'wep' => '魂魄·楼观剑',
				'wepk' => 'WK',
				'wepe' => 75,
				'weps' => 35,
				'wepsk' => array('suit' => 'konpaku'),
				'itm1' => '魂魄·白楼剑',
				'itmk1' => 'WK',
				'itme1' => 66,
				'itms1' => 67,
				'itmsk1' => array('suit' => 'konpaku'),
				'itm2' => '半灵碎片',
				'itmk2' => 'M',
				'itme2' => 1,
				'itms2' => 1,
				),
			),
		),
	27 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 2,
		'gd' => 'm',
		'pls' => 15,
		'mhp' => 1000,
		'msp' => 600,
		'att' => 225,
		'def' => 275,
		'lvl' => 30,
		'proficiency' => 290,
		'skill' => array('Peg'),
		'money' => 5250,
		'arb' => '妖忌·灵服',
		'arbk' => 'DB',
		'arbe' => 65,
		'arbs' => 50,
		'arbsk' => array('suit' => 'konpaku'),
		'arh' => '',
		'arhk' => '',
		'arhe' => 0,
		'arhs' => 0,
		'arf' => '妖忌·布鞋',
		'arfk' => 'DF',
		'arfe' => 30,
		'arfs' => 30,
		'arfsk' => array('suit' => 'konpaku'),
		'ara' => '妖忌·剑鞘',
		'arak' => 'DA',
		'arae' => 35,
		'aras' => 50,
		'arask' => array('suit' => 'konpaku'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '魂魄妖忌',
				'icon' => 33,
				'wep' => '魂魄对剑「白楼观」',
				'wepk' => 'WK',
				'wepe' => 125,
				'weps' => 65,
				'wepsk' => array('multistage' => array(0.6, 0.7), 'suit' => 'konpaku', 'single-buff' => true),
				'itm1' => '半灵碎片',
				'itmk1' => 'M',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	10 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 8,
		'mhp' => 450,
		'msp' => 400,
		'att' => 50,
		'def' => 150,
		'lvl' => 20,
		'proficiency' => 125,
		'skill' => array('Peg'),
		'money' => 1250,
		'arb' => '霊梦·无袖巫女服',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'reimu'),
		'arh' => '霊梦·巨大蝴蝶结',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'reimu'),
		'arf' => '霊梦·巫女鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'reimu'),
		'ara' => '霊梦·袖子',
		'arak' => 'DA',
		'arae' => 15,
		'aras' => 20,
		'arask' => array('suit' => 'reimu'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '博麗霊夢',
				'icon' => 27,
				'wep' => '霊梦·阴阳玉',
				'wepk' => 'WD',
				'wepe' => 60,
				'weps' => 60,
				'wepsk' => array('suit' => 'reimu'),
				'itm1' => '博丽神社の龙井茶',
				'itmk1' => 'HB',
				'itme1' => 250,
				'itms1' => 4,
				'itm2' => '霊梦·御币',
				'itmk2' => 'WP',
				'itme2' => 40,
				'itms2' => 20,
				'itmsk2' => array('suit' => 'reimu'),
				'itm3' => '塞钱',
				'itmk3' => 'M',
				'itme3' => 1,
				'itms3' => 1,
				),
			),
		),
	11 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 13,
		'mhp' => 550,
		'msp' => 400,
		'att' => 150,
		'def' => 100,
		'lvl' => 20,
		'proficiency' => 200,
		'skill' => array('Peg'),
		'money' => 1500,
		'arb' => '幽々子·蝶の羽风',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'yuyuko'),
		'arh' => '幽々子·DreamCast',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'yuyuko'),
		'arf' => '幽々子·黄泉幽冥靴',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 20,
		'arfsk' => array('suit' => 'yuyuko'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '幽々子·环绕幽灵',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 1,
		'artsk' => array('def-buff' => 20, 'suit' => 'yuyuko'),
		'sub' => array
			(
			0 => array
				(
				'name' => '西行寺幽々子',
				'icon' => 25,
				'wep' => '幽々子·凤蝶纹の死枪',
				'wepk' => 'WC',
				'wepe' => 40,
				'weps' => 50,
				'wepsk' => array('suit' => 'yuyuko'),
				'itm1' => '优质樱饼',
				'itmk1' => 'HS',
				'itme1' => 300,
				'itms1' => 2,
				'itm2' => '饕餮之食',
				'itmk2' => 'HH',
				'itme2' => 75,
				'itms2' => 2,
				'itmsk2' => array('poison' => 200),
				'itm3' => '幽灵印花折扇',
				'itmk3' => 'M',
				'itme3' => 1,
				'itms3' => 1,
				),
			),
		),
	12 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 12,
		'mhp' => 450,
		'msp' => 400,
		'att' => 100,
		'def' => 100,
		'lvl' => 20,
		'proficiency' => 75,
		'skill' => array('Peg'),
		'money' => 1250,
		'arb' => '爱丽丝·连衣裙',
		'arbk' => 'DB',
		'arbe' => 55,
		'arbs' => 45,
		'arbsk' => array('suit' => 'alice'),
		'arh' => '爱丽丝·发带',
		'arhk' => 'DH',
		'arhe' => 15,
		'arhs' => 30,
		'arhsk' => array('suit' => 'alice'),
		'arf' => '爱丽丝·舞鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'alice'),
		'ara' => '爱丽丝·魔法书',
		'arak' => 'DA',
		'arae' => 35,
		'aras' => 30,
		'arask' => array('suit' => 'alice'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '爱丽丝·玛格特罗依德',
				'icon' => 26,
				'wep' => '爱丽丝·蓬莱人形',
				'wepk' => 'WD',
				'wepe' => 60,
				'weps' => 90,
				'wepsk' => array('suit' => 'alice'),
				'itm1' => '上海人形',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 2,
				),
			),
		),
	13 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 10,
		'mhp' => 450,
		'msp' => 400,
		'att' => 125,
		'def' => 150,
		'lvl' => 20,
		'proficiency' => 200,
		'skill' => array('Peg'),
		'money' => 1250,
		'arb' => '魔理沙·女仆法袍',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'marisa'),
		'arh' => '魔理沙·巨大魔法帽',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'marisa'),
		'arf' => '魔理沙·靴子',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'marisa'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '魔理沙·星の器',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 1,
		'artsk' => array('att-buff' => 20, 'suit' => 'marisa'),
		'sub' => array
			(
			0 => array
				(
				'name' => '霧雨魔理沙',
				'icon' => 29,
				'wep' => '魔理沙·扫把',
				'wepk' => 'WP',
				'wepe' => 100,
				'weps' => 30,
				'wepsk' => array('suit' => 'marisa'),
				'itm1' => '魔理沙·迷你八卦炉',
				'itmk1' => 'WD',
				'itme1' => 50,
				'itms1' => 20,
				'itmsk1' => array('suit' => 'marisa'),
				'itm2' => 'The Grimoire of Marisa',
				'itmk2' => 'M',
				'itme2' => 1,
				'itms2' => 1,
				),
			),
		),
	14 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 4,
		'mhp' => 375,
		'msp' => 400,
		'att' => 150,
		'def' => 125,
		'lvl' => 20,
		'proficiency' => 125,
		'skill' => array('Peg'),
		'money' => 1300,
		'arb' => '文·记者工作服',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'aya'),
		'arh' => '文·天狗头襟',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'aya'),
		'arf' => '文·跑鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'aya'),
		'ara' => '文·文花贴',
		'arak' => 'DA',
		'arae' => 15,
		'aras' => 30,
		'arask' => array('suit' => 'aya'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '射命丸文',
				'icon' => 23,
				'wep' => '文·团扇',
				'wepk' => 'WP',
				'wepe' => 90,
				'weps' => 15,
				'wepsk' => array('alt' => array('k' => 'K', 'e' => 75), 'suit' => 'aya'),
				'itm1' => '文·相机',
				'itmk1' => 'WP',
				'itme1' => 200,
				'itms1' => 1,
				'itmsk1' => array('suit' => 'aya'),
				'itm2' => '天狗之羽',
				'itmk2' => 'M',
				'itme2' => 1,
				'itms2' => 1,

				),
			),
		),
	17 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 0,
		'gd' => 'f',
		'pls' => 7,
		'mhp' => 300,
		'msp' => 300,
		'att' => 125,
		'def' => 75,
		'lvl' => 13,
		'proficiency' => 100,
		'skill' => array('Peg'),
		'money' => 1500,
		'arb' => '琪露诺·冰晶之翼',
		'arbk' => 'DB',
		'arbe' => 35,
		'arbs' => 45,
		'arbsk' => array('suit' => 'cirno'),
		'arh' => '琪露诺·蓝色蝴蝶结',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'cirno'),
		'arf' => '',
		'arfk' => '',
		'arfe' => 0,
		'arfs' => 0,
		'arfsk' => array('suit' => 'cirno'),
		'ara' => '琪露诺·冰之盾',
		'arak' => 'DA',
		'arae' => 15,
		'aras' => 30,
		'arask' => array('suit' => 'cirno', 'shield' => 10),
		'art' => '琪露诺·算数练习册',
		'artk' => 'A',
		'arte' => 15,
		'arts' => 1,
		'artsk' => array('suit' => 'cirno'),
		'sub' => array
			(
			0 => array
				(
				'name' => '琪露诺',
				'icon' => 34,
				'wep' => '琪露诺·冰冻青蛙',
				'wepk' => 'WC',
				'wepe' => 30,
				'weps' => 40,
				'wepsk' => array('alt' => array('k' => 'D', 'e' => 50), 'suit' => 'cirno'),
				'itm1' => '冰晶核',
				'itmk1' => 'M',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	18 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 5,
		'mhp' => 500,
		'msp' => 400,
		'att' => 155,
		'def' => 155,
		'lvl' => 20,
		'proficiency' => 150,
		'skill' => array('Peg'),
		'money' => 1500,
		'arb' => '上白泽·蓝色教师装',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'keine'),
		'arh' => '上白泽·魔法博士帽',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'keine'),
		'arf' => '',
		'arfk' => '',
		'arfe' => 0,
		'arfs' => 0,
		'ara' => '上白泽·算数教材',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 50,
		'arask' => array('suit' => 'keine'),
		'art' => '上白泽·教师证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 1,
		'arask' => array('suit' => 'keine', 'def-buff'),
		'sub' => array
			(
			0 => array
				(
				'name' => '上白泽慧音',
				'icon' => 35,
				'wep' => '上白泽·历史教材',
				'wepk' => 'WK',
				'wepe' => 55,
				'weps' => 0,
				'wepsk' => array('suit' => 'keine'),
				'itm1' => '上白泽·粉笔头',
				'itmk1' => 'WC',
				'itme1' => 25,
				'itms1' => 35,
				'itmsk1' => array('suit' => 'keine'),
				),
			),
		),
	28 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 2,
		'gd' => 'f',
		'pls' => 5,
		'mhp' => 650,
		'msp' => 400,
		'att' => 175,
		'def' => 125,
		'lvl' => 21,
		'proficiency' => 225,
		'skill' => array('Peg'),
		'money' => 2250,
		'arb' => '上白泽·绿色教师装',
		'arbk' => 'DB',
		'arbe' => 65,
		'arbs' => 45,
		'arbsk' => array('suit' => 'keine'),
		'arh' => '上白泽·白泽角',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 40,
		'arhsk' => array('suit' => 'keine'),
		'arf' => '',
		'arfk' => '',
		'arfe' => 0,
		'arfs' => 0,
		'ara' => '上白泽·国文教材',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		'arask' => array('suit' => 'keine'),
		'art' => '上白泽·教师证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 1,
		'arask' => array('suit' => 'keine', 'att-buff'),
		'sub' => array
			(
			0 => array
				(
				'name' => '上白泽慧音',
				'icon' => 36,
				'wep' => '上白泽·高数教材',
				'wepk' => 'WK',
				'wepe' => 80,
				'weps' => 0,
				'wepsk' => array('suit' => 'keine'),
				'itm1' => '上白泽·粉笔头',
				'itmk1' => 'WC',
				'itme1' => 25,
				'itms1' => 55,
				'itmsk1' => array('suit' => 'keine'),
				),
			),
		),
	21 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 19,
		'mhp' => 600,
		'msp' => 400,
		'att' => 100,
		'def' => 200,
		'lvl' => 20,
		'proficiency' => 175,
		'skill' => array('Peg'),
		'money' => 1750,
		'arb' => '永琳·道术师衣',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'eirin'),
		'arh' => '永琳·护士帽',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'eirin'),
		'arf' => '永琳·护士靴',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'eirin'),
		'ara' => '永琳·医药箱',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		'arask' => array('suit' => 'eirin'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '八意永琳',
				'icon' => 21,
				'wep' => '永琳·月弓',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 50,
				'wepsk' => array('alt' => array('k' => 'P', 'e' => 45), 'suit' => 'eirin'),
				'itm1' => '生薬「国士無双の薬」',
				'itmk1' => 'SY',
				'itme1' => 30,
				'itms1' => 1,
				'itm2' => '蓬莱玉枝',
				'itmk2' => 'Y',
				'itme2' => 1,
				'itms2' => 1,
				),
			),
		),
	22 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 2,
		'gd' => 'f',
		'pls' => 3,
		'mhp' => 600,
		'msp' => 400,
		'att' => 400,
		'def' => 185,
		'lvl' => 20,
		'proficiency' => 367,
		'skill' => array('Peg'),
		'money' => 2000,
		'arb' => '芙兰·七彩水晶之翼',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'scarlet'),
		'arh' => '芙兰·ZUN帽',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'scarlet'),
		'arf' => '芙兰·红鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'scarlet'),
		'ara' => '芙兰·莱瓦汀',
		'arak' => 'DA',
		'arae' => 40,
		'aras' => 12,
		'arask' => array('suit' => 'scarlet'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '芙兰朵露·斯卡雷特',
				'icon' => 30,
				'itm1' => '血之精华',
				'itmk1' => 'Y',
				'itme1' => 25,
				'itms1' => 60,
				'itm2' => 'QED「495年の波纹」',
				'itmk2' => 'SW',
				'itme2' => 350,
				'itms2' => 3,
				),
			),
		),
	23 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 3,
		'mhp' => 600,
		'msp' => 400,
		'att' => 250,
		'def' => 300,
		'lvl' => 20,
		'proficiency' => 220,
		'skill' => array('Peg'),
		'money' => 1750,
		'arb' => '蕾米·黑色恶魔之翼',
		'arbk' => 'DB',
		'arbe' => 60,
		'arbs' => 35,
		'arbsk' => array('suit' => 'scarlet'),
		'arh' => '蕾米·ZUN帽',
		'arhk' => 'DH',
		'arhe' => 30,
		'arhs' => 30,
		'arhsk' => array('suit' => 'scarlet'),
		'arf' => '蕾米·白鞋',
		'arfk' => 'DF',
		'arfe' => 30,
		'arfs' => 20,
		'arfsk' => array('suit' => 'scarlet'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '蕾米·B型血的酒杯',
		'artk' => 'A',
		'arte' => 25,
		'arts' => 1,
		'artsk' => array('att-buff' => 25, 'suit' => 'scarlet'),
		'sub' => array
			(
			0 => array
				(
				'name' => '蕾米莉亚·斯卡雷特',
				'icon' => 31,
				'itm1' => '血之精华',
				'itmk1' => 'Y',
				'itme1' => 25,
				'itms1' => 60,
				'itm2' => '红符「不夜城レッド」',
				'itmk2' => 'SW',
				'itme2' => 80,
				'itms2' => 12,
				),
			),
		),
	24 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 16,
		'mhp' => 750,
		'msp' => 400,
		'att' => 150,
		'def' => 150,
		'lvl' => 20,
		'proficiency' => 225,
		'skill' => array('Peg'),
		'money' => 1750,
		'arb' => '铃仙·夹克短裙装',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'reisen'),
		'arh' => '铃仙·兔耳',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'reisen'),
		'arf' => '铃仙·月球战靴',
		'arfk' => 'DF',
		'arfe' => 30,
		'arfs' => 20,
		'arfsk' => array('suit' => 'reisen'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '铃仙·士兵证明书',
		'artk' => 'A',
		'arte' => 25,
		'arts' => 1,
		'artsk' => array('att-buff' => 25, 'suit' => 'reisen'),
		'sub' => array
			(
			0 => array
				(
				'name' => '铃仙·优昙华院·因幡',
				'icon' => 28,
				'wep' => '铃仙·月之手枪',
				'wepk' => 'WG',
				'wepe' => 95,
				'weps' => 30,
				'wepsk' => array('suit' => 'reisen'),
				'itm1' => '生薬「国士無双の薬」',
				'itmk1' => 'SY',
				'itme1' => 30,
				'itms1' => 1,
				'itm2' => '优昙钵华',
				'itmk2' => 'M',
				'itme2' => 1,
				'itms2' => 1,
				),
			),
		),
	25 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'f',
		'pls' => 2,
		'mhp' => 750,
		'msp' => 400,
		'att' => 150,
		'def' => 175,
		'lvl' => 20,
		'proficiency' => 200,
		'skill' => array('Peg'),
		'money' => 1750,
		'arb' => '咲夜·女仆装',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 45,
		'arbsk' => array('suit' => 'sakuya'),
		'arh' => '咲夜·女仆发箍',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		'arhsk' => array('suit' => 'sakuya'),
		'arf' => '咲夜·女仆鞋',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 20,
		'arfsk' => array('suit' => 'sakuya'),
		'ara' => '咲夜·托盘',
		'arak' => 'DA',
		'arae' => 15,
		'aras' => 30,
		'arask' => array('suit' => 'sakuya'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '十六夜咲夜',
				'icon' => 24,
				'wep' => '咲夜·红魔银刃',
				'wepk' => 'WC',
				'wepe' => 60,
				'weps' => 125,
				'wepsk' => array('suit' => 'sakuya'),
				'itm1' => '月时计',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 3,
				),
			),
		),
	26 => array
		(
		'type' => 4,
		'mode' => 2,
		'num' => 1,
		'round' => 1,
		'gd' => 'm',
		'pls' => 14,
		'mhp' => 1000,
		'msp' => 550,
		'att' => 225,
		'def' => 200,
		'lvl' => 20,
		'proficiency' => 280,
		'skill' => array('Peg'),
		'money' => 3250,
		'arb' => '霖之助·adiStar SL Tee EX',
		'arbk' => 'DB',
		'arbe' => 60,
		'arbs' => 45,
		'arbsk' => array('suit' => 'rinnosuke'),
		'arh' => '霖之助·adiLibria Shield EX',
		'arhk' => 'DH',
		'arhe' => 30,
		'arhs' => 0,
		'arhsk' => array('suit' => 'rinnosuke'),
		'arf' => '霖之助·adiStar Ride EX',
		'arfk' => 'DF',
		'arfe' => 30,
		'arfs' => 20,
		'arfsk' => array('suit' => 'rinnosuke'),
		'ara' => '霖之助·adiStar GT Mens EX',
		'arak' => 'DA',
		'arae' => 30,
		'aras' => 30,
		'arask' => array('suit' => 'rinnosuke'),
		'art' => '霖之助·手绘说明书',
		'artk' => 'A',
		'arte' => 15,
		'arts' => 1,
		'artsk' => array('suit' => 'rinnosuke'),
		'sub' => array
			(
			0 => array
				(
				'name' => '森近 霖之助',
				'icon' => 32,
				'wep' => '霖之助·迷你八卦炉设计图',
				'wepk' => 'WC',
				'wepe' => 10,
				'weps' => 0,
				'wepsk' => array('suit' => 'rinnosuke'),
				'itm1' => '霖之助·迷你八卦炉强化图',
				'itmk1' => 'WC',
				'itme1' => 10,
				'itms1' => 0,
				'itmsk1' => array('suit' => 'rinnosuke'),
				),
			),
		),
	101 => array
		(
		'type' => 4,
		'num' => 1,
		'round' => -1,
		'gd' => 'f',
		'pls' => 8,
		'mhp' => 2000,
		'msp' => 200,
		'att' => 175,
		'def' => 150,
		'lvl' => 30,
		'proficiency' => 225,
		'skill' => array('Immortal', 'Peg'),
		'money' => 2500,
		'arb' => '靈梦·巫女服',
		'arbk' => 'DB',
		'arbe' => 75,
		'arbs' => 50,
		'arbsk' => array('suit' => 'reimu'),
		'arh' => '靈梦·缩水蝴蝶结',
		'arhk' => 'DH',
		'arhe' => 35,
		'arhs' => 30,
		'arhsk' => array('suit' => 'reimu'),
		'arf' => '靈梦·巫女鞋',
		'arfk' => 'DF',
		'arfe' => 35,
		'arfs' => 30,
		'arfsk' => array('suit' => 'reimu'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '博麗靈夢',
				'icon' => 51,
				'wep' => '靈梦·阴阳玉',
				'wepk' => 'WD',
				'wepe' => 100,
				'weps' => 60,
				'wepsk' => array('suit' => 'reimu'),
				'itm1' => '黑历史全系列光盘A',
				'itmk1' => 'M',
				'itme1' => 1,
				'itms1' => 1,
				'itm2' => '靈梦·御币',
				'itmk2' => 'WP',
				'itme2' => 60,
				'itms2' => 20,
				'itmsk2' => array('suit' => 'reimu'),
				'itm3' => '塞钱',
				'itmk3' => 'M',
				'itme3' => 1,
				'itms3' => 1,
				),
			),
		),
	102 => array
		(
		'mode' => 1,
		'num' => 1,
		'round' => -1,
		'gd' => 'f',
		'pls' => 10,
		'mhp' => 2000,
		'msp' => 200,
		'att' => 225,
		'def' => 225,
		'lvl' => 30,
		'proficiency' => 315,
		'skill' => array('Rampart', 'Peg'),
		'money' => 2500,
		'arb' => '魔理沙·魔女服',
		'arbk' => 'DB',
		'arbe' => 75,
		'arbs' => 50,
		'arh' => '魔理沙·魔女帽',
		'arhk' => 'DH',
		'arhe' => 35,
		'arhs' => 30,
		'arhsk' => array('suit' => 'marisa'),
		'arf' => '魔理沙·魔女之靴',
		'arfk' => 'DF',
		'arfe' => 35,
		'arfs' => 30,
		'arfsk' => array('suit' => 'marisa'),
		'ara' => '',
		'arak' => '',
		'arae' => 0,
		'aras' => 0,
		'art' => '魔理沙·Casket of Star',
		'artk' => 'A',
		'arte' => 25,
		'arts' => array('att-buff' => 25, 'suit' => 'marisa'),
		'sub' => array
			(
			0 => array
				(
				'name' => '雾雨魔理沙',
				'icon' => 52,
				'wep' => '魔理沙·魔杖',
				'wepk' => 'WP',
				'wepe' => 125,
				'weps' => 50,
				'itm1' => '黑历史全系列光盘B',
				'itmk1' => 'M',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	103 => array
		(
		'mode' => 1,
		'num' => 1,
		'round' => -1,
		'gd' => 'f',
		'pls' => 1,
		'mhp' => 1667,
		'msp' => 200,
		'att' => 325,
		'def' => 150,
		'lvl' => 35,
		'proficiency' => 275,
		'skill' => array('Shin-Roach', 'Peg'),
		'money' => 2500,
		'arb' => '冴月·风之衣裙',
		'arbk' => 'DB',
		'arbe' => 70,
		'arbs' => 200,
		'arbsk' => array('suit' => 'rin'),
		'arh' => '冴月·花之发饰',
		'arhk' => 'DH',
		'arhe' => 35,
		'arhs' => 125,
		'arhsk' => array('suit' => 'rin'),
		'arf' => '',
		'arfk' => '',
		'arfe' => 0,
		'arfs' => 0,
		'ara' => '冴月·二胡',
		'arak' => 'DA',
		'arae' => 50,
		'aras' => 15,
		'arask' => array('suit' => 'rin'),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '冴月麟',
				'icon' => 53,
				'wep' => '冴月·二胡弓',
				'wepk' => 'WK',
				'wepe' => 150,
				'weps' => 75,
				'wepsk' => array('suit' => 'rin'),
				'itm1' => '黑历史全系列光盘C',
				'itmk1' => 'M',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	109 => array
		(
		'mode' => 1,
		'num' => 1,
		'round' => -1,
		'gd' => 'f',
		'pls' => 99,
		'mhp' => 4000,
		'msp' => 200,
		'att' => 350,
		'def' => 200,
		'lvl' => 30,
		'proficiency' => 300,
		'skill' => array('Thorn', 'Peg'),
		'money' => 10000,
		'arb' => '幽香·红黑格子裙',
		'arbk' => 'DB',
		'arbe' => 100,
		'arbs' => 150,
		'arbsk' => array('anti-P' => 0.6, 'anti-K' => 0.5, 'anti-C' => 0.4, 'anti-G' => 0.7, 'anti-D' => 0.7),
		'arh' => '',
		'arhk' => '',
		'arhe' => 0,
		'arhs' => 0,
		'arf' => '幽香·红鞋',
		'arfk' => 'DF',
		'arfe' => 50,
		'arfs' => 50,
		'ara' => '幽香·伞',
		'arak' => 'DA',
		'arae' => 50,
		'aras' => 50,
		'arask' => array('shield' => 50),
		'art' => '',
		'artk' => '',
		'arte' => 0,
		'arts' => 0,
		'sub' => array
			(
			0 => array
				(
				'name' => '幽香',
				'icon' => 59,
				'wep' => '幽香·Double Spark',
				'wepk' => 'WD',
				'wepe' => 300,
				'weps' => 200,
				'itm1' => '虚拟结界Bug',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	);

?>