(
  _id smallint unsigned NOT NULL auto_increment,
  uid char(11)NOT NULL default '-1',
  type tinyint NOT NULL default '0',
  name char(15) NOT NULL default '',
  gender char(1) NOT NULL default 'm',
  number smallint unsigned NOT NULL default '0',
  icon char(50) NOT NULL default 'img/question.gif',
  club tinyint unsigned NOT NULL default '0',
  `motto` char(30) NOT NULL DEFAULT '',
  `killmsg` char(30) NOT NULL DEFAULT '',
  `lastword` char(30) NOT NULL DEFAULT '',
  skill char(255) NOT NULL default '{}',
  daemontime int(10) unsigned NOT NULL default '0',
  deathtime int(10) unsigned NOT NULL default '0',
  cooldowntime char(255)  NOT NULL default '{}',
  buff varchar(1000) NOT NULL default '[]',
  action char(255) NOT NULL default '{}',
  pose tinyint(1) unsigned NOT NULL default '0',
  tactic tinyint(1) unsigned NOT NULL default '0',
  hp int unsigned NOT NULL default '0',
  mhp int unsigned NOT NULL default '0',
  sp int unsigned NOT NULL default '0',
  msp int unsigned NOT NULL default '0',
  att smallint unsigned NOT NULL default '0',
  def smallint unsigned NOT NULL default '0',
  baseatt smallint unsigned NOT NULL default '0',
  basedef smallint unsigned NOT NULL default '0',
  area tinyint unsigned NOT NULL default '0',
  lvl tinyint unsigned NOT NULL default '0',
  `exp` smallint unsigned NOT NULL default '0',
  `upexp` smallint unsigned NOT NULL default '0',
  money mediumint unsigned NOT NULL default '0',
  killnum smallint unsigned NOT NULL default '0',
  proficiency char(255) not null default '{}',
  `teamID` char(24) not null default '-1',
  collecting char(255) NOT NULL default '{}',
  capacity smallint unsigned not null default '5',
  package varchar(1000) NOT NULL default '[]',
  equipment varchar(1000) NOT NULL default '{}',
  
  rage int unsigned NOT NULL default '0',

  PRIMARY KEY  (_id),
  INDEX TYPE (type, number),
  INDEX NAME (name, type)
	
)