(
  `_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(15) NOT NULL DEFAULT '',
  `password` char(32) NOT NULL DEFAULT '',
  `groupid` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lastgame` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ip` char(15) NOT NULL DEFAULT '',
  `credits` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `token` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `validgames` smallint(5) unsigned NOT NULL DEFAULT '0',
  `wingames` smallint(5) unsigned NOT NULL DEFAULT '0',
  `gender` char(1) NOT NULL DEFAULT 'm',
  `icon` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `iconuri` varchar(50) NOT NULL default 'img/question.gif',
  `club` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `motto` varchar(32) NOT NULL DEFAULT '',
  `killmsg` varchar(32) NOT NULL DEFAULT '',
  `lastword` varchar(32) NOT NULL DEFAULT '',
  `achievement` varchar(1000) NOT NULL DEFAULT '[]',
  PRIMARY KEY (`_id`),
  INDEX RANK (`credits`),
  UNIQUE KEY `username` (`username`)
)