<?php

$npcinfo = array
	( 
	1 => array
		(
		'mode' => 1,
		'num' => 1,
		'club' => 0,
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 3000,
		'msp' => 200,
		'att' => 200,
		'def' => 300,
		'lvl' => 30,
		'proficiency' => 200,
		'skill' => array('Peg'),
		'money' => 5000,
		'arb' => '特种部队迷彩服',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 100,
		'arh' => '源氏之盔',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 100,
		'arf' => 'Nike的Air Force1',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 100,
		'ara' => '米奇的手袋',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 100,
		'art' => '教师证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('def-buff' => 20),
		'sub' => array
			(
			0 => array
				(
				'name' => '金发',
				'icon' => 1,
				'wep' => '水素粒子水铁炮',
				'wepk' => 'WG',
				'wepe' => 100,
				'weps' => 200,
				'itm1' => '游戏解除钥匙',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	2 => array
		(
		'mode' => 1,
		'num' => 4,
		'club' => 0,
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 2000,
		'msp' => 200,
		'att' => 150,
		'def' => 200,
		'lvl' => 20,
		'proficiency' => 100,
		'skill' => array('Peg'),
		'money' => 2000,
		'arb' => '军服α',
		'arbk' => 'DB',
		'arbe' => 40,
		'arbs' => 100,
		'arh' => '军帽α',
		'arhk' => 'DH',
		'arhe' => 20,
		'arhs' => 100,
		'arf' => '军靴α',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 100,
		'ara' => '军用手套α',
		'arak' => 'DA',
		'arae' => 20,
		'aras' => 100,
		'art' => '教师证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('def-buff' => 20),
		'sub' => array
			(
			0 => array
				(
				'name' => '甲',
				'icon' => 11,
				'wep' => '军用狙击枪α',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			1 => array
				(
				'name' => '乙',
				'icon' => 12,
				'wep' => '军用狙击枪α',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			2 => array
				(
				'name' => '丙',
				'icon' => 13,
				'wep' => '军用狙击枪α',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			3 => array
				(
				'name' => '丁',
				'icon' => 14,
				'wep' => '军用狙击枪α',
				'wepk' => 'WG',
				'wepe' => 75,
				'weps' => 200,
				),
			),
		),
	3 => array
		(
		'mode' => 2,
		'num' => 100,
		'club' => 0,
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 300,
		'msp' => 200,
		'att' => 100,
		'def' => 150,
		'lvl' => 10,
		'proficiency' => 20,
		'skill' => array(),
		'money' => 500,
		'arb' => '军服β',
		'arbk' => 'DB',
		'arbe' => 30,
		'arbs' => 30,
		'arh' => '军帽β',
		'arhk' => 'DH',
		'arhe' => 10,
		'arhs' => 30,
		'arf' => '军靴β',
		'arfk' => 'DF',
		'arfe' => 10,
		'arfs' => 30,
		'ara' => '军用手套β',
		'arak' => 'DA',
		'arae' => 10,
		'aras' => 30,
		'art' => '士兵证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('att-buff' => 20),
		'sub' => array
			(
			0 => array
				(
				'name' => '甲',
				'icon' => 11,
				'wep' => '小米加步枪β',
				'wepk' => 'WG',
				'wepe' => 50,
				'weps' => 50,
				),
			1 => array
				(
				'name' => '乙',
				'icon' => 12,
				'wep' => '少林木杖',
				'wepk' => 'WP',
				'wepe' => 30,
				'weps' => 15,
				),
			2 => array
				(
				'name' => '丙',
				'icon' => 13,
				'wep' => '砍柴刀',
				'wepk' => 'WK',
				'wepe' => 35,
				'weps' => 10,
				),
			3 => array
				(
				'name' => '丁',
				'icon' => 14,
				'wep' => '小李飞刀',
				'wepk' => 'WC',
				'wepe' => 10,
				'weps' => 50,
				),
			),
		),
	);


?>